config/routes.rb
require "sidekiq/pro/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  root to: 'home#index'

  post 'login', to: "users#login", as: :login
  post 'logout', to: "users#logout", as: :logout
  get '/users/:address', to: "users#show", as: :user
  post '/users/sync_flip_records', to: "users#sync_flip_records", as: :sync_user_flip_records
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fliper.rb
class Fliper < ApplicationRecord
  has_many :nft_flip_records

  def successful_rate
    "#{(nft_flip_records.successful_rate * 100).round(3)} %"
  end

  def flip_count
    nft_flip_records.count
  end

  def flip_gap
    nft_flip_records.sum(&:gap) / flip_count rescue 0
  end

  def flip_revenue
    nft_flip_records.sum(&:revenue)
  end

  def rank
    rank = Fliper.all.sort_by{|f| f.successful_rate}.reverse.index(self)
    rank < 0 ? "-" : rank + 1
  end
end

app/models/nft.rb
class Nft < ApplicationRecord
  has_many :nft_flip_records
end

app/models/nft_flip_record.rb
class NftFlipRecord < ApplicationRecord
  belongs_to :nft
  belongs_to :fliper

  ETH_PAYMENT = ["ETH", "WETH"]

  def is_eth_payment?
    bought_coin.in?(ETH_PAYMENT) && sold_coin.in?(ETH_PAYMENT)
  end

  def is_sol_payment?
    bought_coin == "SOL" && sold_coin == "SOL"
  end

  def same_coin?
    bought_coin == sold_coin || is_eth_payment?
  end

  def self.successful
    select{|n| n.roi_usd > 0 || n.same_coin? && n.roi > 0}
  end

  def self.failed
    select{|n| n.roi_usd < 0 || n.same_coin? && n.roi < 0}
  end

  def self.successful_rate
    all.size == 0 ? 0 : successful.size.to_f / all.size.to_f
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    user = Fliper.where(address: params[:address]).first_or_create
    session[:user_id] = user.id
    SyncFlipRecordsJob.perform_later(user)

    redirect_to user_path(user.address), notice: "Sync data successfully, please reload page after 5 minutes"
  end

  def logout
    session[:user_id] = nil if session[:user_id]

    render json: {success: true}
  end

  def show
    @user = Fliper.find_by(address: params[:address])

    data = FlipChartService.new(start_at: Time.now - 1.week, fliper_address: @user.address)
    @flip_data_chart = data.get_flip_data
    @flip_profit_chart = data.get_flip_profit
  end

  def sync_flip_records
    user = Fliper.find_by id: session[:user_id]

    SyncFlipRecordsJob.perform_later(user)

    redirect_to user_path(user.address), notice: "Sync data successfully, please reload page after 5 minutes"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= Fliper.find_by(id: session[:user_id])
  end

  def date_format(datetime)
    datetime.strftime('%Y-%m-%d')
  end

  def get_logo(logo_url)
    logo_url || asset_url("placeholder.png")
  end

  def is_admin?
    admin_ids = ENV.fetch("ADMIN_IDS"){""}.split(',')
    current_user && current_user.id.to_s.in?(admin_ids)
  end

  def address_format(address)
    address[6...-4] = "...."
    address
  end

  def decimal_format(data)
    data.to_f.round(3)
  end

  def humanize_gap(gap)
    gap = gap.to_f
    if gap < 86400
      hours = gap / 3600
      "#{hours.round(2)} hours"
    else
      days = (gap / 86400).to_i
      hours = (gap - days * 86400) / 3600
      "#{days} days #{hours.round(2)} hours"
    end
  end

  def home_path
    current_user ? user_path(current_user.address) : root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="text-center">
  <div class="welcome-intro">
    <h1>Keep up with all the important happenings in the web3world</h1>
    <%= button_tag "Connect MetaMask", class: "btn btn-warning metamask_login" unless current_user %>
  </div>
</div>

app/views/layouts/_notices.html.erb
<% type_mapping = { alert: :danger, notice: :success } %>
<% flash.each do |k, v| %>
  <% k = type_mapping[k.to_sym] if type_mapping[k.to_sym].present?  %>
  <div class="alert alert-<%= k %> alert-dismissible fade show mt-2" role="alert">
    <strong><%= sanitize(v.to_s) %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fliper Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="is-sidebar">
    <main class="page-wrapper">
      <div id="spinner" class="hide">
        <%= image_tag("loading.svg") %>
      </div>
      <header class="header navbar navbar-expand-lg navbar-light bg-light navbar-shadow navbar-sticky" data-scroll-header data-fixed-element>
        <div class="container px-0 px-xl-2">
          <button class="navbar-toggler ms-n2 me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#primaryMenu">
            <span class="navbar-toggler-icon"></span>
          </button>
          <%= link_to "Fliper Portfolio", home_path, class: "navbar-brand flex-shrink-0 order-lg-1 mx-auto ms-lg-0 pe-lg-2 me-lg-4" %>
          <div class="d-flex align-items-center order-lg-3 ms-lg-auto loginBtns">
            <div class="navbar-tool dropdown connect-btn">
              <%= button_tag "Connect MetaMask", class: "btn btn-warning metamask_login" %>
            </div>
            <div class="navbar-tool dropdown hide">
              <a href="#" role="button" class="navbar-tool-label">
                <span id="login_address"></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                <% if current_user %>
                  <li>
                    <%= link_to "#", class: "dropdown-item", id: "btn-logout" do %>
                      <i class="ai-log-out fs-base me-2"></i>
                      <%= t("views.action.logout") %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="offcanvas offcanvas-collapse order-lg-2" id="primaryMenu">
            <div class="offcanvas-header navbar-shadow">
              <button class="btn-close lead" type="button" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <!-- Menu-->
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to t("views.title.home"), home_path, class: "nav-link" %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </header>
      <%= render "layouts/notices" %>
      <%= yield %>
    </main>
    <footer class="footer">
      <div class="bg-secondary py-4 py-md-3">
        <div class="container d-md-flex align-items-center justify-content-center pt-3">
            <p class="fs-sm pt-2 mb-3"><span class="text-black opacity-50 me-1">© All rights reserved. Made by Coinbay Networks, Inc</span></p>
          </div>
        </div>
      </div>
    </footer>
    <button class="btn btn-primary btn-sm sidebar-toggle" type="button" data-bs-toggle="offcanvas" data-bs-target="#blog-sidebar"><i class="ai-sidebar fs-base me-2"></i><%= t("views.label.sidebar") %></button>
  </body>
</html>

app/views/users/_flip_data_chart.html.erb
<div class="mt-3">
  <canvas id="flipDataChart" style="height: 300px; width: 100%" data-data="<%= @flip_data_chart.to_json %>" ></canvas>
</div>

<script>
document.addEventListener('turbolinks:load', () => {
  var canvas = document.getElementById('flipDataChart');
  if(canvas){
    const ctx = canvas.getContext('2d');
    const chart_data = JSON.parse(ctx.canvas.dataset.data)
    const flip_data = Object.values(chart_data)
    const profitDataArray = flip_data.flat().map(i => {
                              if (i[0] > 0){
                                return {x: new Date(i[1]), y: i[0]}
                              }
                            })
    const lossDataArray = flip_data.flat().map(i => {
                            if (i[0] < 0){
                              return {x: new Date(i[1]), y: i[0]}
                            }
                          })

    new Chart(ctx, {
      type: 'scatter',
      data: {
        datasets: [
          {
            label: "Profit",
            data: profitDataArray.filter(Boolean),
            borderColor: "rgb(75, 192, 192)",
            backgroundColor: "rgba(75, 192, 192, 0.5)"
          },
          {
            label: "Loss",
            data: lossDataArray.filter(Boolean),
            borderColor: "rgb(255, 99, 132)",
            backgroundColor: "rgba(255, 99, 132, 0.5)"
          }
        ],
      },
      options: {
        scales: {
          x: {
            type: 'time',
            display: true,
            offset: true,
            time: {
              unit: 'day'
            }
          }
        },
        responsive: false
      }
    });
  }
})
</script>

app/views/users/_flip_profit_chart.html.erb
<div class="mt-3">
  <canvas id="flipCountChart" style="height: 300px; width: 100%" data-data="<%= @flip_profit_chart.to_json %>" ></canvas>
</div>

<script>
document.addEventListener('turbolinks:load', () => {
  var canvas = document.getElementById('flipCountChart');
  if(canvas){
    var ctx = canvas.getContext('2d');
    var chart_data = JSON.parse(ctx.canvas.dataset.data)
    const flip_data = Object.values(chart_data)
    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: Object.keys(chart_data),
        datasets: [
          {
            label: "Total profit",
            data: flip_data.map(i => {
              return i.total_profit
            }),
            tension: 0.4,
            borderColor: "rgb(75, 192, 192)",
            backgroundColor: "rgba(75, 192, 192, 0.5)",
            yAxisID: 'y'
          }
        ],
      },
      options: {
        scales: {
          x: {
            grid: {
              display: false,
            }
          },
          y: {
            position: 'left',
            ticks: {
              maxTicksLimit: 5
            },
          }
        },
        responsive: false,
        plugins: {
          tooltip: {
            callbacks: {
              label: function(context) {
                return ''
              }
            }
          }
        }
      }
    });
  }
})
</script>

app/views/users/show.html.erb
<div class="container zindex-5 pb-4 mb-md-3 mt-5 mx-auto col-8">
  <div class="row">
    <!-- Sidebar-->
    <div class="mb-lg-0 position-relative">
      <div class="bg-light rounded-3 shadow-lg">
        <div class="px-4 py-4 mb-1 text-center">
          <h6 class="mb-0 pt-1"><%= @user.address %></h6></span>
        </div>
        <div class="d-lg-none px-4 pb-4 text-center"><a class="btn btn-primary px-5 mb-2" href="#account-menu" data-bs-toggle="collapse"><i class="ai-menu me-2"></i>Account menu</a></div>
        <div class="d-lg-block collapse pb-2" id="account-menu">
          <h3 class="d-block bg-secondary fs-sm fw-semibold text-muted mb-0 px-4 py-3">Dashboard</h3>
          <a class="d-flex align-items-center nav-link-style px-4 py-3">
            Rank<span class="text-muted fs-sm fw-normal ms-auto"><%= @user.rank %></span>
          </a>
          <a class="d-flex align-items-center nav-link-style px-4 py-3">
            Successful Rate<span class="text-muted fs-sm fw-normal ms-auto"><%= @user.successful_rate %></span>
          </a>
          <a class="d-flex align-items-center nav-link-style px-4 py-3 border-top">
            Flip Count<span class="text-muted fs-sm fw-normal ms-auto"><%= @user.flip_count %></span>
          </a>
          <a class="d-flex align-items-center nav-link-style px-4 py-3 border-top">
            Flip Gap<span class="text-muted fs-sm fw-normal ms-auto"><%= humanize_gap @user.flip_gap %></span>
          </a>
          <a class="d-flex align-items-center nav-link-style px-4 py-3 border-top">
            Flip Revenue<span class="text-muted fs-sm fw-normal ms-auto"><%= decimal_format @user.flip_revenue %></span>
          </a>
        </div>
      </div>
      <div class="chart">
        <%= render "flip_data_chart" %>
        <%= render "flip_profit_chart" %>
      </div>
      <div id="syncBtn">
        <%= link_to "Sync", sync_user_flip_records_path, class: "btn btn-warning", method: :post %>
      </div>
    </div>
  </div>
</div>